# Generated by Django 6.0.5 on 2026-06-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('FARMER', 'Farmer'), ('STAFF', 'Staff'), ('DELIVERY', 'Delivery Guy'), ('ADMIN', 'Admin')], default='CLIENT', max_length=20),
        ),
    ]
